# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.PositiveSmallIntegerField(choices=[(1, 'Boo'), (2, 'Foo'), (3, 'Bar'), (4, 'Baz')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='ws_lock.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTypeVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.PositiveSmallIntegerField(choices=[(1, 'Boo'), (2, 'Foo'), (3, 'Bar'), (4, 'Baz')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_types', to='auth.group')),
            ],
            options={
                'unique_together': {('item_type', 'group')},
            },
        ),
    ]
