name: Tests

on: push

jobs:
  runtest:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        PYTHONPATH=. py.test --ds=example.settings
