name: Tests

on: push

jobs:
  runtest:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: library/postgres:alpine
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        channels:
          - '4.2.0'
          - '4.1.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
        pip install 'channels==${{ matrix.channels}}'
    - name: Run tests
      run: |
        PYTHONPATH=. py.test --ds=example.settings
